
---
- name: Install Node Exporter on all Kubernetes nodes
  hosts: kubernetes
  become: yes
  tasks:
    - name: Install Node Exporter
      script: ./scripts/install-node-exporter.sh
      args:
        creates: /usr/local/bin/node_exporter

    - name: Verify Node Exporter is running
      uri:
        url: "http://{{ ansible_host }}:9100/metrics"
        method: GET
      register: node_check
      retries: 3
      delay: 5

- name: Setup kube-state-metrics on master
  hosts: master
  become: no
  tasks:
    - name: Deploy kube-state-metrics
      script: ./scripts/setup-kube-state-metrics.sh
      environment:
        KUBECONFIG: "/home/ubuntu/.kube/config"

    - name: Verify kube-state-metrics endpoint
      uri:
        url: "http://{{ ansible_host }}:30080/metrics"
        method: GET
      retries: 5
      delay: 10

- name: Setup cAdvisor on master (via kubectl)
  hosts: master
  become: no
  tasks:
    - name: Deploy standalone cAdvisor
      script: ./scripts/setup-standalone-cadvisor.sh
      environment:
        KUBECONFIG: "/home/ubuntu/.kube/config"

    - name: Wait for cAdvisor pods to be ready
      pause:
        seconds: 30

    - name: Verify cAdvisor endpoints on all nodes
      uri:
        url: "http://{{ hostvars[item]['ansible_host'] }}:8080/metrics"
        method: GET
        timeout: 10
      register: cadvisor_check
      retries: 5
      delay: 10
      loop: "{{ groups['kubernetes'] }}"
      ignore_errors: yes

    - name: Display cAdvisor verification results
      debug:
        msg: |
          cAdvisor endpoint {{ hostvars[item.item]['ansible_host'] }}:8080 - {{ 'OK' if item.status == 200 else 'FAILED' }}
      loop: "{{ cadvisor_check.results }}"
      when: cadvisor_check.results is defined

- name: Generate configuration files
  hosts: localhost
  tasks:
    - name: Create Prometheus config
      template:
        src: ./templates/prometheus-config.yml.j2
        dest: ./prometheus-kubernetes-config.yml

    - name: Create Prometheus update script
      template:
        src: ./templates/update-prometheus.sh.j2
        dest: ./scripts/update-prometheus-complete.sh
        mode: '0755'

    - name: Create setup summary
      template:
        src: ./templates/summary.md.j2
        dest: ./monitoring-setup-complete.md

    - name: Show completion message
      debug:
        msg: |
          ================================================================
          🎉 MONITORING SETUP COMPLETED!
          ================================================================
          
          ✅ Node Exporter installed on all nodes
          ✅ kube-state-metrics deployed
          ✅ cAdvisor deployed as DaemonSet
          ✅ Configuration files generated
          
          📋 NEXT STEPS:
          1. SSH to Prometheus server (192.168.1.200)
          2. Run: sudo ./scripts/update-prometheus-complete.sh
          3. Import Grafana dashboards
          
          📁 FILES CREATED:
          - prometheus-kubernetes-config.yml
          - scripts/update-prometheus-complete.sh
          - monitoring-setup-complete.md
          
          🔗 ENDPOINTS TO TEST:
          {% for host in groups['kubernetes'] %}
          - Node Exporter: http://{{ hostvars[host]['ansible_host'] }}:9100/metrics
          - cAdvisor: http://{{ hostvars[host]['ansible_host'] }}:8080/metrics
          {% endfor %}
          - kube-state-metrics: http://{{ hostvars['master']['ansible_host'] }}:30080/metrics
          ================================================================