apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-config
  namespace: kube-system
data:
  config.json: |
    [
      {
        "clusterID": "8a8c14c8-f022-48bd-96f8-892cddb2dc43",
        "monitors": ["10.0.0.4:6789", "10.0.0.5:6789", "10.0.0.6:6789"]
      }
    ]
