apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi-cephfs
type: Opaque
stringData:
  # Using admin credentials for compatibility with Ceph Squid
  # (Same approach as RBD due to go-ceph library issues)
  adminID: "admin"
  adminKey: "AQCKiNloCtRhNRAArqvVfeOSW+4OvFmennHtzg=="

  # For production with compatible Ceph version, use dedicated user:
  # userID: "k8sfs"
  # userKey: "YOUR_K8SFS_KEY_HERE"
