apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-config
  namespace: ceph-csi-cephfs
  labels:
    app.kubernetes.io/managed-by: Helm
    app: ceph-csi-cephfs
    chart: ceph-csi-cephfs-3.7.2
    heritage: Helm
    release: ceph-csi-cephfs
  annotations:
    meta.helm.sh/release-name: ceph-csi-cephfs
    meta.helm.sh/release-namespace: ceph-csi-cephfs
data:
  ceph.conf: |
    [global]
      auth_cluster_required = cephx
      auth_service_required = cephx
      auth_client_required = cephx
      mon_host = 10.0.0.4:6789,10.0.0.5:6789,10.0.0.6:6789
      fsid = 8a8c14c8-f022-48bd-96f8-892cddb2dc43
  keyring: |
    [client.admin]
      key = AQCKiNloCtRhNRAArqvVfeOSW+4OvFmennHtzg==
