apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-ceph-rbd
---
apiVersion: v1
kind: Pod
metadata:
  name: app-using-pvc
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo Hello > /mnt/data/hello.txt && sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /mnt/data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: my-pvc

