---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany  # RWX - can be mounted by multiple pods
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-cephfs-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-writer
  namespace: default
  labels:
    app: cephfs-test
    role: writer
spec:
  containers:
    - name: writer
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
        - |
          echo "Writer pod started at $(date)" > /mnt/cephfs/writer.txt
          while true; do
            echo "$(date): Writing from writer pod" >> /mnt/cephfs/shared.log
            sleep 5
          done
      volumeMounts:
        - name: cephfs-volume
          mountPath: /mnt/cephfs
  volumes:
    - name: cephfs-volume
      persistentVolumeClaim:
        claimName: cephfs-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-reader-1
  namespace: default
  labels:
    app: cephfs-test
    role: reader
spec:
  containers:
    - name: reader
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
        - |
          echo "Reader-1 started at $(date)" > /mnt/cephfs/reader-1.txt
          while true; do
            echo "=== Reader-1 at $(date) ==="
            echo "Files in /mnt/cephfs:"
            ls -lh /mnt/cephfs/
            echo ""
            echo "Last 5 lines of shared.log:"
            tail -5 /mnt/cephfs/shared.log 2>/dev/null || echo "shared.log not found yet"
            echo ""
            sleep 10
          done
      volumeMounts:
        - name: cephfs-volume
          mountPath: /mnt/cephfs
  volumes:
    - name: cephfs-volume
      persistentVolumeClaim:
        claimName: cephfs-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: cephfs-reader-2
  namespace: default
  labels:
    app: cephfs-test
    role: reader
spec:
  containers:
    - name: reader
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
        - |
          echo "Reader-2 started at $(date)" > /mnt/cephfs/reader-2.txt
          while true; do
            echo "Reader-2: Monitoring shared filesystem..."
            cat /mnt/cephfs/writer.txt 2>/dev/null || echo "writer.txt not found"
            sleep 15
          done
      volumeMounts:
        - name: cephfs-volume
          mountPath: /mnt/cephfs
  volumes:
    - name: cephfs-volume
      persistentVolumeClaim:
        claimName: cephfs-pvc
