#!/bin/bash
# Stop Full Hadoop Ecosystem
# Generated by Ansible on {{ ansible_date_time.iso8601 }}

set -e

echo " Stopping Hadoop Big Data Ecosystem..."
echo "========================================"

# Source environment
source /home/ubuntu/.bashrc

# Stop services in reverse order

# Stop Elasticsearch
echo " Stopping Elasticsearch..."
pkill -f elasticsearch || echo "⚠️  Elasticsearch not running"

# Stop Solr
echo " Stopping Solr..."
if [[ -x "{{ solr_home }}/bin/solr" ]]; then
    {{ solr_home }}/bin/solr stop -all || echo "⚠️  Solr not running"
else
    echo "⚠️  Solr not found, skipping..."
fi

# Stop Flink
echo " Stopping Flink..."
if [[ -x "{{ flink_home }}/bin/stop-cluster.sh" ]]; then
    {{ flink_home }}/bin/stop-cluster.sh || echo "⚠️  Flink not running"
else
    echo "⚠️  Flink not found, skipping..."
fi

# Stop Spark
echo "⚡ Stopping Spark..."
if [[ -x "{{ spark_home }}/sbin/stop-all.sh" ]]; then
    {{ spark_home }}/sbin/stop-all.sh || echo "⚠️  Spark not running"
else
    echo "⚠️  Spark not found, skipping..."
fi

# Stop Kafka
echo " Stopping Kafka..."
if [[ -x "{{ kafka_home }}/bin/kafka-server-stop.sh" ]]; then
    {{ kafka_home }}/bin/kafka-server-stop.sh || echo "⚠️  Kafka not running"
else
    echo "⚠️  Kafka not found, skipping..."
fi

# Stop HBase
echo "️  Stopping HBase..."
if [[ -x "{{ hbase_home }}/bin/stop-hbase.sh" ]]; then
    {{ hbase_home }}/bin/stop-hbase.sh || echo "⚠️  HBase not running"
else
    echo "⚠️  HBase not found, skipping..."
fi

# Stop Hadoop YARN
echo " Stopping Hadoop YARN..."
if [[ -x "{{ hadoop_home }}/sbin/stop-yarn.sh" ]]; then
    {{ hadoop_home }}/sbin/stop-yarn.sh || echo "⚠️  YARN not running"
fi

# Stop Hadoop HDFS
echo "️  Stopping Hadoop HDFS..."
if [[ -x "{{ hadoop_home }}/sbin/stop-dfs.sh" ]]; then
    {{ hadoop_home }}/sbin/stop-dfs.sh || echo "⚠️  HDFS not running"
fi

# Stop Zookeeper last
echo " Stopping Zookeeper..."
if [[ -x "{{ zookeeper_home }}/bin/zkServer.sh" ]]; then
    {{ zookeeper_home }}/bin/zkServer.sh stop || echo "⚠️  Zookeeper not running"
else
    echo "⚠️  Zookeeper not found, skipping..."
fi

# Clean up any remaining processes
echo " Cleaning up remaining processes..."
sleep 5

# Kill any stubborn Java processes
pkill -f "hadoop" || true
pkill -f "spark" || true
pkill -f "hbase" || true
pkill -f "kafka" || true
pkill -f "zookeeper" || true

echo ""
echo "✅ Hadoop Ecosystem shutdown completed!"
echo "========================================"

# Verify shutdown
echo " Checking for remaining processes..."
remaining=$(ps aux | grep -E "(hadoop|spark|hbase|kafka|zookeeper|elasticsearch|solr)" | grep java | grep -v grep | wc -l)
if [[ $remaining -eq 0 ]]; then
    echo "✅ All processes stopped successfully"
else
    echo "⚠️  $remaining processes still running:"
    ps aux | grep -E "(hadoop|spark|hbase|kafka|zookeeper|elasticsearch|solr)" | grep java | grep -v grep | awk '{print "  " $11}'
fi
