#!/bin/bash
# Start Full Hadoop Ecosystem
# Generated by Ansible on {{ ansible_date_time.iso8601 }}

set -e

echo " Starting Hadoop Big Data Ecosystem..."
echo "========================================"

# Source environment
source /home/ubuntu/.bashrc

# Start Zookeeper first
echo " Starting Zookeeper..."
if [[ -x "{{ zookeeper_home }}/bin/zkServer.sh" ]]; then
    {{ zookeeper_home }}/bin/zkServer.sh start
    sleep 10
    echo "✅ Zookeeper started"
else
    echo "⚠️  Zookeeper not found, skipping..."
fi

# Start Hadoop services (NameNode first)
echo "️  Starting Hadoop HDFS..."
if [[ -x "{{ hadoop_home }}/sbin/start-dfs.sh" ]]; then
    {{ hadoop_home }}/sbin/start-dfs.sh
    sleep 15
    echo "✅ HDFS started"
else
    echo "❌ Hadoop not found!"
    exit 1
fi

echo " Starting Hadoop YARN..."
if [[ -x "{{ hadoop_home }}/sbin/start-yarn.sh" ]]; then
    {{ hadoop_home }}/sbin/start-yarn.sh
    sleep 10
    echo "✅ YARN started"
fi

# Start HBase
echo "️  Starting HBase..."
if [[ -x "{{ hbase_home }}/bin/start-hbase.sh" ]]; then
    {{ hbase_home }}/bin/start-hbase.sh
    sleep 15
    echo "✅ HBase started"
else
    echo "⚠️  HBase not found, skipping..."
fi

# Start Kafka
echo " Starting Kafka..."
if [[ -x "{{ kafka_home }}/bin/kafka-server-start.sh" ]]; then
    nohup {{ kafka_home }}/bin/kafka-server-start.sh {{ kafka_home }}/config/server.properties > /data/logs/kafka.log 2>&1 &
    sleep 10
    echo "✅ Kafka started"
else
    echo "⚠️  Kafka not found, skipping..."
fi

# Start Spark
echo "⚡ Starting Spark..."
if [[ -x "{{ spark_home }}/sbin/start-all.sh" ]]; then
    {{ spark_home }}/sbin/start-all.sh
    sleep 10
    echo "✅ Spark started"
else
    echo "⚠️  Spark not found, skipping..."
fi

# Start Flink
echo " Starting Flink..."
if [[ -x "{{ flink_home }}/bin/start-cluster.sh" ]]; then
    {{ flink_home }}/bin/start-cluster.sh
    sleep 10
    echo "✅ Flink started"
else
    echo "⚠️  Flink not found, skipping..."
fi

# Start Solr
echo " Starting Solr..."
if [[ -x "{{ solr_home }}/bin/solr" ]]; then
    {{ solr_home }}/bin/solr start -p 8983
    sleep 10
    echo "✅ Solr started"
else
    echo "⚠️  Solr not found, skipping..."
fi

# Start Elasticsearch
echo " Starting Elasticsearch..."
if [[ -x "{{ elasticsearch_home }}/bin/elasticsearch" ]]; then
    nohup {{ elasticsearch_home }}/bin/elasticsearch > /data/logs/elasticsearch.log 2>&1 &
    sleep 15
    echo "✅ Elasticsearch started"
else
    echo "⚠️  Elasticsearch not found, skipping..."
fi

# Wait for services to stabilize
echo "⏳ Waiting for services to stabilize..."
sleep 30

# Verify services
echo " Verifying services..."
echo ""
echo "Web Interfaces:"
{% for host in groups['namenode'] %}
echo "   Hadoop NameNode:        http://{{ hostvars[host]['ansible_host'] }}:9870"
echo "   YARN ResourceManager:   http://{{ hostvars[host]['ansible_host'] }}:8088"
echo "  ⚡ Spark Master:           http://{{ hostvars[host]['ansible_host'] }}:8080"
echo "  ️  HBase Master:           http://{{ hostvars[host]['ansible_host'] }}:16010"
echo "   Solr:                   http://{{ hostvars[host]['ansible_host'] }}:8983"
echo "   Elasticsearch:          http://{{ hostvars[host]['ansible_host'] }}:9200"
{% endfor %}

echo ""
echo " Hadoop Ecosystem startup completed!"
echo "========================================"

# Show running processes
echo ""
echo " Running Big Data processes:"
ps aux | grep -E "(hadoop|spark|hbase|kafka|zookeeper|elasticsearch|solr)" | grep java | grep -v grep | awk '{print "  " $11}' | sort | uniq

echo ""
echo "✅ All services should now be running!"
echo " Check the web interfaces above to verify everything is working correctly."
